.PHONY: build install test cross

build:
	go build -ldflags="-s -w" -o t$(if $(filter windows,$(shell go env GOOS)),.exe,) ./...

install:
	go install ./...

test:
	go test -v ./...

cross:
	mkdir -p dist
	GOOS=windows GOARCH=amd64 go build -ldflags="-s -w" -o dist/t-windows-amd64.exe ./...
	GOOS=darwin  GOARCH=amd64 go build -ldflags="-s -w" -o dist/t-darwin-amd64 ./...
	GOOS=darwin  GOARCH=arm64 go build -ldflags="-s -w" -o dist/t-darwin-arm64 ./...
	GOOS=linux   GOARCH=amd64 go build -ldflags="-s -w" -o dist/t-linux-amd64 ./...
